export const PRODUCTS_GET_REQUEST = 'PRODUCTS_GET_REQUEST';
export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
export const PRODUCTS_GET_FAIL = 'PRODUCTS_GET_FAIL';

export const TOP_PRODUCTS_GET_REQUEST = 'TOP_PRODUCTS_GET_REQUEST';
export const TOP_PRODUCTS_GET_SUCCESS = 'TOP_PRODUCTS_GET_SUCCESS';
export const TOP_PRODUCTS_GET_FAIL = 'TOP_PRODUCTS_GET_FAIL';
