export const PRODUCTS_GET_REQUEST = 'PRODUCTS_GET_REQUEST';
export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
export const PRODUCTS_GET_FAIL = 'PRODUCTS_GET_FAIL';

export const PRODUCT_GET_REQUEST = 'PRODUCT_GET_REQUEST';
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAIL = 'PRODUCT_GET_FAIL';

export const RELATED_PRODUCTS_GET_REQUEST = 'RELATED_PRODUCTS_GET_REQUEST';
export const RELATED_PRODUCTS_GET_SUCCESS = 'RELATED_PRODUCTS_GET_SUCCESS';
export const RELATED_PRODUCTS_GET_FAIL = 'RELATED_PRODUCTS_GET_FAIL';

export const TOP_PRODUCTS_GET_REQUEST = 'TOP_PRODUCTS_GET_REQUEST';
export const TOP_PRODUCTS_GET_SUCCESS = 'TOP_PRODUCTS_GET_SUCCESS';
export const TOP_PRODUCTS_GET_FAIL = 'TOP_PRODUCTS_GET_FAIL';
